services:
  web:
    build: .
    volumes:
      - .:/code
  web_run:
    extends:
      service: web
    command: sh -c "python /code/myshop/manage.py migrate &&
             python /code/myshop/manage.py createsuperuser --noinput || true &&
             python /code/myshop/manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: password
    ports:
      - "8000:8000"